// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPIBlueModas.Repository;

namespace WebAPIBlueModas.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPIBlueModas.Dominio.Cliente", b =>
                {
                    b.Property<string>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(80);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("ClienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("WebAPIBlueModas.Dominio.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClienteId");

                    b.HasKey("CompraId");

                    b.HasIndex("ClienteId");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("WebAPIBlueModas.Dominio.CompraProduto", b =>
                {
                    b.Property<int>("CompraProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompraId");

                    b.Property<int>("ProdutoId");

                    b.HasKey("CompraProdutoId");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ComprasProdutos");
                });

            modelBuilder.Entity("WebAPIBlueModas.Dominio.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Imagem")
                        .HasMaxLength(200);

                    b.Property<string>("Nome")
                        .HasMaxLength(200);

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            ProdutoId = 1,
                            Imagem = "http://lucasduarte.me/produto/tenis-nike-sb-charge-cnvs-masculino-img.jpg",
                            Nome = "Tênis Nike SB Charge CNVS",
                            Preco = 189.99m
                        },
                        new
                        {
                            ProdutoId = 2,
                            Imagem = "http://lucasduarte.me/produto/calcao-adams-futaw-masculino-img.jpg",
                            Nome = "Calção Adams Futaw",
                            Preco = 21.99m
                        },
                        new
                        {
                            ProdutoId = 3,
                            Imagem = "http://lucasduarte.me/produto/tenis-adidas-vs-pace-masculino-img.jpg",
                            Nome = "Tênis adidas VS Pace",
                            Preco = 189.99m
                        },
                        new
                        {
                            ProdutoId = 4,
                            Imagem = "http://lucasduarte.me/produto/regata-basica-feminina.jpg",
                            Nome = "Regata Feminina Básica Com Alça Fina",
                            Preco = 17.99m
                        },
                        new
                        {
                            ProdutoId = 5,
                            Imagem = "http://lucasduarte.me/produto/blusa-manga-curta-feminina.jpg",
                            Nome = "Blusa Feminina Manga Curta Com Gola Redonda",
                            Preco = 19.99m
                        },
                        new
                        {
                            ProdutoId = 6,
                            Imagem = "http://lucasduarte.me/produto/camisa-masculino-manga-curta.jpg",
                            Nome = "Camisa Masculino Manga Curta Regular Algodão",
                            Preco = 69.99m
                        },
                        new
                        {
                            ProdutoId = 7,
                            Imagem = "http://lucasduarte.me/produto/camiseta-star-wars.jpg",
                            Nome = "Camiseta Masculina Slim Manga Curta Star Wars",
                            Preco = 45.99m
                        },
                        new
                        {
                            ProdutoId = 8,
                            Imagem = "http://lucasduarte.me/produto/camiseta-contraste-azul.jpg",
                            Nome = "Camiseta Masculina Manga Curta Azul",
                            Preco = 29.99m
                        },
                        new
                        {
                            ProdutoId = 9,
                            Imagem = "http://lucasduarte.me/produto/blusa-feminina-manga-curta-com-gola-alta-cinza.jpg",
                            Nome = "Blusa Feminina Manga Curta Com Gola Alta Cinza",
                            Preco = 39.99m
                        });
                });

            modelBuilder.Entity("WebAPIBlueModas.Dominio.Compra", b =>
                {
                    b.HasOne("WebAPIBlueModas.Dominio.Cliente", "Cliente")
                        .WithMany("Compras")
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("WebAPIBlueModas.Dominio.CompraProduto", b =>
                {
                    b.HasOne("WebAPIBlueModas.Dominio.Compra", "Compra")
                        .WithMany("ComprasProdutos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebAPIBlueModas.Dominio.Produto", "Produto")
                        .WithMany("ComprasProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
